import { studio } from './config.mjs';
import { layout, esc } from './site.mjs';
const email = `<a href="mailto:${esc(studio.email)}">${esc(studio.email)}</a>`;
export const documents = {
  privacy: { title: 'Privacy policy', sections: [
    ['Scope and data controller', `<p>This policy covers the magikstudio.me studio website and communications with the studio. The data controller is the entity operating Magikstudio. Its legal name, address, and country of establishment must be completed before publication.</p><p>Games will have separate information tailored to their features. Historical documents from the reference repository remain at their original addresses with their original publisher attribution.</p>`],
    ['Data and purposes', `<p>The website offers no accounts, payments, or signup forms. Its code includes no advertising or audience analytics.</p><p>If you email us, your email address, any name you provide, and your message are used to respond to your request. The copy-address button uses your clipboard only when you activate it, without transmitting its contents to the studio.</p><p>The hosting provider may process technical logs including IP addresses, requested pages, dates, and browser information to deliver and secure the website. Log settings and retention periods must be specified for the chosen hosting service.</p>`],
    ['Legal bases and retention', `<p>Where the GDPR applies, handling a request may rely on our legitimate interest in responding to enquiries (Article 6(1)(f)), or on pre-contractual steps you request (Article 6(1)(b)), depending on its nature.</p><p>Data should be kept for as long as necessary for its purpose, subject to legal obligations and the defence of legal claims. Specific retention periods for communications and technical logs must be set by the operator before publication.</p>`],
    ['Providers and transfers', `<p>Recipients include people authorised to respond and the necessary email and hosting providers. Their identities, processing locations, and any safeguards for transfers outside the European Economic Area must be completed based on the services actually selected.</p><p>A future App Store link will take you to Apple’s service, which has its own <a href="https://www.apple.com/legal/privacy/en-ww/" target="_blank" rel="noopener noreferrer">privacy policy</a>.</p>`],
    ['Cookies and storage', `<p>The current website uses no tracking cookies, local storage, or session storage. Fonts and images are hosted with the site. No form sends data to the reference website’s newsletter service. Animation preferences and playful interactions stay in memory and are reset when the page reloads.</p><p>If features or trackers are added, this policy must be updated and any required choices offered before activation.</p>`],
    ['Your rights', `<p>Subject to applicable law, including Articles 15–22 of the GDPR where it applies, you may request access, rectification, erasure, restriction, or portability, or object to processing. Rights concerning automated decisions apply where such decisions exist. The current website makes no automated decisions with legal effects.</p><p>For questions or to exercise your rights, contact ${email}. This address must still be confirmed as operational. Where processing relies on consent, you may withdraw it.</p><p>You may lodge a complaint with the competent supervisory authority, including the <a href="https://www.cnil.fr/en" target="_blank" rel="noopener noreferrer">CNIL</a> in France.</p>`],
  ]},
  terms: { title: 'Terms of use', sections: [
    ['The Magikstudio website', '<p>This website introduces Magikstudio, its game projects, and its contact details. No account is required. Once confirmed, the operator’s full legal identity will appear in the legal notice.</p>'],
    ['Projects and availability', '<p>Projects in development may change. A presentation does not guarantee a release date, feature, price, or availability on a platform. Current illustrations are creative studio concepts, not screenshots of a released game.</p><p>Any future App Store downloads or purchases will be governed by the distribution terms and licences applicable to the game. These terms cover the studio website only.</p>'],
    ['Use and access', '<p>Use the site without disrupting its operation, attempting unauthorised access to its systems, or transmitting unlawful or malicious content. Access may be interrupted for maintenance or technical reasons. You remain responsible for your connection costs.</p>'],
    ['Content and rights', `<p>Content, creative work, and distinctive signs are protected to the extent provided by applicable law. Viewing them does not transfer intellectual property rights. Statutory exceptions continue to apply.</p><p>For reuse requiring permission, contact ${email}. Third-party trademarks, including Apple and App Store, belong to their respective owners.</p>`],
    ['Links and liability', '<p>External services have their own rules and are operated by third parties. Liability is assessed under applicable law. Nothing on this page seeks to exclude liability that cannot lawfully be excluded or limit mandatory consumer rights.</p>'],
    ['Privacy and updates', '<p>See our <a href="/privacy/">privacy policy</a> for website-related processing. These terms may change as features evolve. The version date appears on this page.</p><p>The country of establishment is still to be confirmed. This draft therefore does not designate a national governing law or an exclusive court.</p>'],
  ]},
  legal: { title: 'Legal notice', sections: [
    ['Operator', '<p>Studio name: Magikstudio. Intended domain: magikstudio.me.</p><p>The operator’s legal name, legal form, address, country of establishment, and applicable registration and VAT numbers must be completed before publication.</p>'],
    ['Publication and contact', `<p>The name of the person responsible for publication must be added. Intended contact address: ${email}, subject to confirmation by the operator.</p>`],
    ['Hosting', '<p>The hosting provider’s name, address, and contact details must be added once the production service has been selected. The current project is a local preview.</p>'],
    ['Credits', '<p>Technical foundation adapted from the indie-core-dev repository. Bricolage Grotesque and Plus Jakarta Sans fonts are served locally. The 3D illustration was created with an image-generation tool and is used as studio concept art.</p><p>Historical documents from the reference repository retain their original attribution. The original games are not presented as Magikstudio productions.</p>'],
  ]},
};
export function legalPage(key) {
  const doc = documents[key];
  return layout({title:doc.title,description:`${doc.title} for the Magikstudio website. Information about the website, its use, and personal data.`,route:`/${key}/`,noindex:studio.legalStatus === 'draft',body:`<article class="shell doc"><a class="back-link" href="/">← Back to the studio</a><div class="eyebrow">MAGIKSTUDIO / THE USEFUL STUFF</div><h1>${doc.title}</h1><p class="doc-date">Working draft · ${studio.updated}</p><div class="doc-layout"><nav class="toc" aria-label="Contents">${doc.sections.map(([title],i)=>`<a href="#section-${i+1}">${String(i+1).padStart(2,'0')} / ${title}</a>`).join('')}</nav><div class="doc-content"><div class="legal-notice"><strong>To be completed before publication</strong><p>The operator must confirm business information, service providers, and retention periods. This document covers the studio website; it does not replace a policy specific to each game.</p></div>${doc.sections.map(([title,body],i)=>`<section id="section-${i+1}"><h2>${title}</h2>${body}</section>`).join('')}</div></div></article>`});
}
