import { studio, games } from './config.mjs';
export const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const star = '<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M16 2h8l1 10 8-6 5 7-9 6 10 3-3 8-10-4 2 11-9 1-1-11-8 7-5-7 9-7-11-2 2-9 11 4z" fill="currentColor"/></svg>';
export const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const apple = '<svg viewBox="0 0 24 28" aria-hidden="true"><path d="M19.6 14.8c0-3 2.5-4.5 2.6-4.6-1.4-2-3.6-2.3-4.4-2.4-1.8-.2-3.5 1.1-4.4 1.1-.9 0-2.3-1.1-3.8-1.1-2 0-3.9 1.2-4.9 3-2.1 3.6-.5 9 1.5 11.9 1 1.4 2.1 2.8 3.6 2.7 1.4-.1 2-1 3.8-1 1.7 0 2.2 1 3.8 1 1.6 0 2.6-1.4 3.5-2.8 1.1-1.6 1.6-3.2 1.6-3.3-.1 0-2.9-1.1-2.9-4.5ZM16.7 5.9c.8-1 1.4-2.4 1.3-3.9-1.2.1-2.7.8-3.6 1.8-.8.9-1.5 2.4-1.3 3.8 1.4.1 2.7-.7 3.6-1.7Z" fill="currentColor"/></svg>';
export const validStore = game => typeof game.appStoreUrl === 'string' && /^https:\/\/apps\.apple\.com\/[a-zA-Z0-9]/.test(game.appStoreUrl);
export const storeButton = game => validStore(game)
  ? `<a class="store-link" href="${esc(game.appStoreUrl)}" target="_blank" rel="noopener noreferrer">${apple}<span><small>Discover on</small>App Store</span>${arrow}</a>`
  : `<div class="store-pending">${apple}<span><small>Coming to</small>App Store</span><span class="pending-tag">SOON</span></div>`;
const nav = current => `<a class="skip" href="#main">Skip to content</a><header class="nav" id="nav"><div class="shell nav-in"><a class="brand" href="/" aria-label="Magikstudio home">${star}<span>magikstudio<span class="brand-dot">.</span></span></a><nav class="nav-links" aria-label="Main navigation"><a href="/#games" ${current === 'games' ? 'aria-current="page"' : ''}>Our games</a><a href="/about/" ${current === 'about' ? 'aria-current="page"' : ''}>The studio</a><a class="nav-cta" href="/contact/">Say hello ${arrow}</a></nav><button class="burger" aria-label="Open menu" aria-expanded="false" aria-controls="mobmenu"><span></span><span></span></button></div><nav class="mobmenu" id="mobmenu" aria-label="Mobile navigation" hidden><a href="/#games">Our games</a><a href="/about/">The studio</a><a href="/contact/">Say hello ${arrow}</a></nav></header>`;
const footer = `<footer class="foot"><div class="shell"><div class="footer-main"><div><a class="brand" href="/" aria-label="Magikstudio home">${star}<span>magikstudio.</span></a><p>Little games.<br>Happiness to go.</p></div><div class="footer-links"><span>EXPLORE</span><a href="/#games">Our games</a><a href="/about/">The studio</a><a href="/contact/">Get in touch</a></div><div class="footer-links"><span>THE USEFUL STUFF</span><a href="/privacy/">Privacy</a><a href="/terms/">Terms of use</a><a href="/legal/">Legal notice</a></div><a class="footer-top" href="#top" aria-label="Back to top">↑</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Magikstudio</span><button class="motion-toggle" aria-pressed="false" hidden>Pause animations</button><span>Made with care. And a little magik. <span class="tiny-star">✳</span></span></div></div></footer>`;
export function layout({ title, description, body, route = '/', current = '', noindex = false }) {
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} — Magikstudio</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#fffdf7"><link rel="canonical" href="${studio.url}${route}">${noindex ? '<meta name="robots" content="noindex">' : ''}<meta property="og:title" content="${esc(title)} — Magikstudio"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${studio.url}/assets/magikstudio/casual-world.jpg"><meta property="og:type" content="website"><meta property="og:url" content="${studio.url}${route}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fonts/bricolage-grotesque-800-0.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/magikstudio/site.css?v=playful-en-1"><script src="/assets/magikstudio/app.js?v=playful-en-1" defer></script></head><body><div id="top"></div>${nav(current)}<main id="main">${body}</main>${footer}</body></html>`;
}
export const projectArt = (className = '') => `<div class="project-art ${className}"><img src="/assets/magikstudio/casual-world.jpg" width="1536" height="1024" loading="lazy" alt="Studio concept art: playful characters and colorful puzzles in a whimsical world"><span class="art-corner">DREAMED UP AT MAGIKSTUDIO</span><div class="project-lock"><span>A LITTLE SOMETHING IS COMING…</span><strong>Coming<br>soon<span> ✦</span></strong></div><span class="art-caption">STUDIO CONCEPT ART · GAME IN DEVELOPMENT</span><span class="art-cross" aria-hidden="true">+</span></div>`;
export function homePage() {
  return layout({title:'Little games. Big happy moments.', description:'Magikstudio is an independent casual game studio. Explore our playful world and our next mobile game, currently in development.', body:`
<section class="casual-hero"><img class="hero-world" src="/assets/magikstudio/casual-world.jpg" width="1536" height="1024" alt="Two cheerful characters play with puzzle blocks on pastel floating islands" fetchpriority="high"><div class="hero-shade"></div><div class="floating-goodies" aria-hidden="true"><span class="goodie goodie-star">✦</span><span class="goodie goodie-ring"></span><span class="goodie goodie-square"></span></div><div class="shell casual-content"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span> INDEPENDENT STUDIO · CASUAL GAMES</div><h1>Little games.<br><span class="electric">Big happy<br>moments.</span></h1><p>Easy-to-love games. Little challenges to enjoy. <br>And that feeling of “just one more round!”</p><div class="hero-actions"><a class="btn btn-primary" href="#games">Explore our games ${arrow}</a><a class="hero-about" href="/about/">Meet the studio <span>↗</span></a></div><div class="hero-note"><span class="note-line" aria-hidden="true"></span> Made with care. Played with a smile.</div></div><button class="happy-sticker" data-magic aria-label="Add a little magik"><span>tap for a little</span><strong>happy<br>magik!</strong><span aria-hidden="true">✦</span></button><span class="magic-feedback sr-only" role="status"></span></div><div class="hero-bottom shell"><a href="#games"><span class="scroll-icon">↓</span> HAPPINESS STARTS HERE</a><span>A LITTLE PEEK INTO OUR IMAGINATION <b>✦</b></span></div></section>
<div class="manifest-strip"><div class="shell"><span>Little challenges</span>${star}<span>Big smiles</span>${star}<span>Playful minds</span>${star}<span>A sprinkle of magik</span>${star}</div></div>
<section class="section shell" id="games"><div class="section-top"><span class="eyebrow">01 / OUR GAMES</span><span class="index-note">SOMETHING GOOD IS GROWING</span></div><div class="section-heading"><h2>Your next<br><span class="purple">happy little break.</span></h2><p>A new world is taking shape.<br>We can’t wait to show you around.</p></div>${games.map((g, i) => `<article class="featured-game">${projectArt()}<div class="game-copy"><div class="eyebrow"><span class="dot"></span> ${esc(g.status.toUpperCase())}</div><span class="game-number">${esc(g.label)}</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p><div class="game-tags"><span>Original creation</span><span>Mobile</span></div><div class="game-bottom"><a class="text-link" href="/games/${esc(g.slug)}/">Meet the project ${arrow}</a>${validStore(g) ? `<a class="game-soon" href="${esc(g.appStoreUrl)}" target="_blank" rel="noopener noreferrer">Available on the App Store ↗</a>` : '<span class="game-soon">App Store · Coming soon</span>'}</div></div></article>`).join('')}<div class="under-card"><span>✳</span> The best is yet to play. First game screenshots coming soon.</div></section>
<section class="studio-section" id="studio"><div class="shell studio-grid"><div class="studio-art"><span class="studio-art-label">OUR SUPERPOWER? CURIOSITY.</span><div class="studio-orbit orbit-one"></div><div class="studio-orbit orbit-two"></div><div class="studio-core">M<span>✦</span></div><span class="studio-art-foot">GOOD IDEAS LOVE TO PLAY.</span><span class="studio-art-number">∞</span></div><div class="studio-copy"><div class="eyebrow">02 / BEHIND THE MAGIK</div><h2>Small team.<br><span class="purple">Wonderfully<br>big ideas.</span></h2><p>At Magikstudio, we take play seriously. Especially the fun part.</p><p>We’re an independent studio with a soft spot for simple ideas, smile-inducing details, and experiences worth sharing. From the first sketch to the tiniest animation, that spirit goes into everything we make.</p><a class="text-link" href="/about/">A little more about us ${arrow}</a></div></div></section>
<section class="section shell approach"><div class="section-top"><span class="eyebrow">03 / HOW WE PLAY</span><span class="index-note">HAPPINESS IS IN THE DETAILS.</span></div><h2>Easy to pick up.<br><span class="purple">Hard to put down.</span></h2><div class="values"><article><div class="value-icon coral">✳</div><span>01</span><h3>A spark of an idea.</h3><p>An intuitive move. A curious little rule. We look for that spark that makes you want to give it a go.</p></article><article><div class="value-icon lilac">↗</div><span>02</span><h3>Care in every detail.</h3><p>The colors, the rhythm, the feel of a move. Little details make a big difference.</p></article><article><div class="value-icon mint">∞</div><span>03</span><h3>Players come first.</h3><p>Try, listen, and try again. Our ideas come to life when they meet the way you play.</p></article></div></section>
<section class="contact-band shell"><div><div class="eyebrow">AN IDEA? A FRIENDLY HELLO?</div><h2>Let’s make<br><span>a little magik.</span></h2><p>Let’s talk games, creativity, and good things to make together.</p></div><a class="contact-ball" href="/contact/" aria-label="Contact Magikstudio">${arrow}<span>LET’S TALK</span></a></section>
`});
}
export function aboutPage() {
  return layout({title:'The studio',description:'Meet Magikstudio, an independent studio making games with curiosity, care, and plenty of heart.',route:'/about/',current:'about',body:`<section class="page-hero shell"><a class="back-link" href="/">← Home</a><div class="eyebrow">THE STUDIO</div><h1>Creative by nature.<br><span class="purple">Playful, always.</span></h1><p class="page-lede">Magikstudio started with a simple wish: to bring a little happiness to everyday breaks.</p></section><section class="shell about-story"><div class="about-image"><img src="/assets/magikstudio/casual-world.jpg" width="1536" height="1024" alt="Our casual world: floating islands, puzzles, and lovable characters"><span>A LITTLE PEEK INTO OUR IMAGINATION</span></div><div><span class="eyebrow">OUR WAY OF THINKING</span><h2>Curious by nature.<br><span class="purple">Playful, always.</span></h2><p>We love building, trying, and making things better. A game often starts with a small question: what if this shape moved differently? What if one rule changed everything?</p><p>We bring game design, development, and art together. We aim for experiences that feel welcoming from the first tap, with enough depth to keep you coming back.</p><p>Our next game is in development. Its name, screenshots, and App Store link will appear here as we reveal more.</p><a class="btn btn-primary" href="/#games">See our next game ${arrow}</a></div></section><section class="quote shell"><span>✳</span><h2>“Just one more round.”<br><span class="purple">Our favorite compliment.</span></h2></section>`});
}
export function gamePage(game) {
  return layout({title:'Our next game',description:'A new mobile game is taking shape at Magikstudio. Meet the project and check back for its future App Store release.',route:`/games/${game.slug}/`,current:'games',body:`<section class="page-hero shell"><a class="back-link" href="/#games">← All our games</a><div class="eyebrow"><span class="dot"></span> ${esc(game.status.toUpperCase())}</div><h1>A brand-new game.<br><span class="purple">Happy little moments.</span></h1><p class="page-lede">${esc(game.description)}</p></section><section class="shell project-page">${projectArt()}<div class="project-info"><div><span class="eyebrow">${esc(game.label)} / MAGIKSTUDIO ORIGINAL</span><h2>${esc(game.name)}</h2><p>We’ll reveal the game’s name, how it plays, and its first screenshots here. For now, this is a little space for what’s coming next.</p></div><div>${storeButton(game)}<p class="store-help">${validStore(game) ? 'This link opens the official game listing.' : 'We’ll add the official listing as soon as it’s available. Downloads aren’t open yet.'}</p></div></div><div class="faq"><h2>Before you play.</h2><details><summary>When can I play?<span>+</span></summary><p>We haven’t announced a release date yet. We’ll update this page when we’re ready to share it.</p></details><details><summary>Is this what the final game looks like?<span>+</span></summary><p>These illustrations explore the studio’s creative world. Actual game screenshots will replace them when the game is announced.</p></details><details><summary>How can I ask the studio a question?<span>+</span></summary><p>Head to our <a href="/contact/">contact page</a> and say hello. We’d love to hear from you.</p></details></div></section>`});
}
export function contactPage() {
  return layout({title:'Say hello',description:'Contact Magikstudio with a question about our games, a collaboration idea, or a friendly hello.',route:'/contact/',body:`<section class="page-hero shell"><a class="back-link" href="/">← Home</a><div class="eyebrow">GOOD THINGS START WITH HELLO</div><h1>Got something in mind?<br><span class="purple">We’re all ears.</span></h1><p class="page-lede">A game question, something we could make together, or just a friendly hello? Drop us a line.</p><div class="contact-card"><div class="contact-star">${star}</div><div><span class="eyebrow">STUDIO CONTACT</span><a class="email" href="mailto:${esc(studio.email)}">${esc(studio.email)}</a><span class="contact-help">Opens your email app to write to the studio.</span></div><button class="copy-email" data-copy-email="${esc(studio.email)}" aria-label="Copy email address">Copy ${arrow}</button></div><p class="copy-feedback" role="status" aria-live="polite"></p><div class="contact-bottom"><p>For questions about your data,<br>take a look at our privacy policy too.</p><a class="text-link" href="/privacy/">Privacy ${arrow}</a></div></section>`});
}
